# Generated by Django 5.2.5 on 2025-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('category', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100)),
                ('website_link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('publications', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
