# Generated by Django 5.2.5 on 2025-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
